<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-18 at 13:42:51.
 */
class Ab_Utils_StringTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Ab_Utils_String
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Ab_Utils_String;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ab_Utils_String::camelize
     * @todo   Implement testCamelize().
     */
    public function testCamelize()
    {
		$res = Ab_Utils_String::camelize('aaa_bBb_ccC');
		$this->assertEquals('AaaBbbCcc' , $res);
    }

    /**
     * @covers Ab_Utils_String::underscore
     * @todo   Implement testUnderscore().
     */
    public function testUnderscore()
    {
		$res = Ab_Utils_String::underscore('AaaBbbCcc');
		$this->assertEquals('aaa_bbb_ccc' , $res);
    }

    /**
     * @covers Ab_Utils_String::convertEncoding
     * @todo   Implement testConvertEncoding().
     */
    public function testConvertEncoding()
    {
		$utf8 = "\xE3\x81\x82\xE3\x81\x82\xE3\x81\x82\xE3\x81\x82\xE3\x81\x82";
		$euc = "\xA4\xA2\xA4\xA2\xA4\xA2\xA4\xA2\xA4\xA2";
		$res = Ab_Utils_String::convertEncoding($utf8, "euc-jp","utf-8");
		$this->assertEquals($euc, $res);
		
		$ar = array($euc, $euc,$euc);
		$res = Ab_Utils_String::convertEncoding($ar, "utf-8","euc-jp");
		$this->assertEquals(array($utf8,$utf8,$utf8),$res);
    }

    /**
     * @covers Ab_Utils_String::escapeCsv
     * @todo   Implement testEscapeCsv().
     */
    public function testEscapeCsv()
    {
		$res = Ab_Utils_String::escapeCsv('"あああ","いいい","ううう"');
		$this->assertEquals('”あああ”，”いいい”，”ううう”', $res);
    }
}
