<?php

//require_once dirname(__FILE__).'/../src/lib/application/config/init.php';
require_once APPLICATION_PATH . '/../library/Ab/Device.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-11 at 12:15:41.
 * 日本語テスト　あああああ
 */
class Ab_DeviceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Ab_Device
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->_user_agent = $_SERVER["HTTP_USER_AGENT"] = 
				"Mozilla/5.0 (Linux; U; Android 1.6; ja-jp; IS01 Build/S2151) AppleWebKit/528.5 (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1";
        $this->object = Ab_Device::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ab_Device::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
		// this test is skipped
    }

    /**
     * @covers Ab_Device::getTypeString
     * @todo   Implement testGetTypeString().
     */
    public function testGetTypeString()
    {
		$ret = $this->object->getTypeString();
		$this->assertEquals("sp", $ret);
    }

    /**
     * @covers Ab_Device::isSmartphone
     * @todo   Implement testIsSmartphone().
     */
    public function testIsSmartphone()
    {
		$ret = $this->object->isSmartphone();
		$this->assertTrue($ret);
    }

    /**
     * @covers Ab_Device::isAndroid
     * @todo   Implement testIsAndroid().
     */
    public function testIsAndroid()
    {
		$ret = $this->object->isAndroid();
		$this->assertTrue($ret);
    }

    /**
     * @covers Ab_Device::isIphone
     * @todo   Implement testIsIphone().
     */
    public function testIsIphone()
    {
		$ret = $this->object->isIphone();
		$this->assertTrue($ret); // wrong sample
    }

    /**
     * @covers Ab_Device::isMobile
     * @todo   Implement testIsMobile().
     */
    public function testIsMobile()
    {
		$ret = $this->object->isMobile();
		$this->assertFalse($ret);
    }

    /**
     * @covers Ab_Device::isDoCoMo
     * @todo   Implement testIsDoCoMo().
     */
    public function testIsDoCoMo()
    {
		$ret = $this->object->isDoCoMo();
		$this->assertFalse($ret);
    }

    /**
     * @covers Ab_Device::isEZweb
     * @todo   Implement testIsEZweb().
     */
    public function testIsEZweb()
    {
		$ret = $this->object->isEZweb();
		$this->assertFalse($ret);
    }

    /**
     * @covers Ab_Device::isSoftBank
     * @todo   Implement testIsSoftBank().
     */
    public function testIsSoftBank()
    {
		$ret = $this->object->isSoftbank();
		$this->assertFalse($ret);
    }

    /**
     * @covers Ab_Device::getCarrier
     * @todo   Implement testGetCarrier().
     */
    public function testGetCarrier()
    {
		$ret = $this->object->getCarrier();
		$this->assertEquals("NonMobile",$ret);
    }

    /**
     * @covers Ab_Device::getModel
     * @todo   Implement testGetModel().
     */
    public function testGetModel()
    {
		$ret = $this->object->getModel();
		$this->assertNull($ret);
    }

    /**
     * @covers Ab_Device::getUid
     * @todo   Implement testGetUid().
     */
    public function testGetUid()
    {
		$ret = $this->object->getUid();
		$this->assertNull($ret);
    }

    /**
     * @covers Ab_Device::getUserAgent
     * @todo   Implement testGetUserAgent().
     */
    public function testGetUserAgent()
    {
		$ret = $this->object->getUserAgent();
		$this->assertEquals($this->_user_agent, $ret);
    }
}
